trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  jdkVersion: 18.0.1.1
  jdkVersionMajor: 18
  jdkDownloadUrl: https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_windows-x64_bin.zip
  jdkInstallPackage: '$(Agent.TempDirectory)\jdk-$(jdkVersion).zip'

steps:
- task: UsePythonVersion@0
  displayName: Setup Python3
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- task: PythonScript@0
  displayName: Download JDK
  inputs:
    scriptSource: 'inline'
    script: |
      from urllib.request import urlretrieve
      urlretrieve("$(jdkDownloadUrl)", r"$(jdkInstallPackage)")
- task: JavaToolInstaller@0
  displayName: Install JDK
  inputs:
    versionSpec: $(jdkVersionMajor)
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: $(jdkInstallPackage)
    jdkDestinationDirectory: '$(Agent.TempDirectory)'
    cleanDestinationDirectory: false
- task: Gradle@2
  displayName: Build and Test
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build test release'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(Agent.TempDirectory)\JAVA_HOME_$(jdkVersionMajor)_x64_jdk-$(jdkVersion)_zip\jdk-$(jdkVersion)'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  displayName: Copy Build Artifacts
  inputs:
    SourceFolder: 'build\release'
    Contents: 'Mobitra-*.zip*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Build Artifacts'
    publishLocation: 'Container'
- task: GitHubRelease@1
  displayName: Publish GitHub Release
  inputs:
    gitHubConnection: 'mobitra'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    releaseNotesSource: 'inline'
    releaseNotesInline: '[Changelog](https://github.com/mpaulse/mobitra/blob/master/CHANGELOG.md)'
    assets: '$(Build.ArtifactStagingDirectory)/Mobitra-*.zip*'
    addChangeLog: false