trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  jdkVersion: 13.0.1
  jdkVersionMajor: 13
  jdkDownloadUrl: https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz
  jdkInstallPackage: '$(Agent.TempDirectory)/jdk-$(jdkVersion).tar.gz'

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      from urllib.request import urlretrieve
      urlretrieve("$(jdkDownloadUrl)", "$(jdkInstallPackage)")
- task: JavaToolInstaller@0
  inputs:
    versionSpec: $(jdkVersionMajor)
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: $(jdkInstallPackage)
    jdkDestinationDirectory: '$(Agent.TempDirectory)/jdk'
    cleanDestinationDirectory: true
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(Agent.TempDirectory)/jdk/jdk-$(jdkVersion)'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
